server:
  port: 8888

spring:
  application:
    name: micsrv-web
  main:
    show-banner: false

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta}%clr(---){faint} %clr([%15.15t][%32X{_traceMark_}]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n %wEx'

dubbo:
  consumer:
    check: false
  registry:
    address: zookeeper://localhost:2181
    check: false
