spring:
  application:
    name: micsrv-job-service

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta}%clr(---){faint} %clr([%15.15t][%32X{_traceMark_}]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n %wEx'

dubbo:
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: zookeeper://localhost:2181
    check: false
  consumer:
    check: false

elasticjob:
  regCenter:
    serverList: localhost:2181
    namespace: ${spring.application.name}
  jobScheduler:
    matedataSimpleJob:
      cron: 0/5 * * * * ?
      shardingTotalCount: 1
      shardingItemParameters: 0=A
    complexMarkSimpleJob:
      cron: 0/5 * * * * ?
      shardingTotalCount: 1
      shardingItemParameters: 0=A
